name: Backup Master Branch

on:
  push:
    branches:
      - master

jobs:
  backup_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Push code to backup branch
        run: |
          git checkout -b backup-branch
          git push --force origin backup-branch
