name: Backup Master Branch

on:
  push:
    branches:
      - master

jobs:
  backup_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use your Node.js version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version appropriate for your project

      - name: Install dependencies
        run: npm install
        
      - name: Run Build
        run: npm run build

      - name: Increment version
        run: |
          current_version=$(jq -r '.version' package.json)
          IFS='.' read -r -a version_parts <<< "$current_version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.$(printf "%03d" ${version_parts[2]})"
          jq ".version = \"$new_version\"" package.json > package.tmp.json && mv package.tmp.json package.json
      
      - name: Commit version change
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git add dist
          git commit -m "Increment version to $new_version"

      - name: Push updated code to backup branch
        run: |
          git checkout -b backup-branch
          git push --force origin backup-branch
