name: Deploy to Amazon Linux

on:
  # Trigger on push to the specific branch
  push:
    branches:
      - backup-branch

  # Allow manual trigger for testing purposes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy dist folder
        run: |
          sudo mkdir -p /usr/share/nginx/html
          sudo cp -r dist/* /usr/share/nginx/html/

      - name: Set permissions for Nginx
        run: |
          sudo chmod -R 755 /usr/share/nginx/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
