name: Deploy to Amazon Linux

on:
  # Trigger on push to the specific branch
  push:
    branches:
      - master

  # Allow manual trigger for testing purposes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Print Node.js version
        run: node -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove existing repository directory
        run: |
          sudo rm -rf /home/ec2-user/repository
      - name: Build project
        run: |
          npm install
          npm run build
          
      - name: List directory contents after build
        run: |
          ls -la /home/ec2-user/repository
          ls -la /home/ec2-user/repository/dist

      - name: Verify dist directory exists
        run: |
          if [ -d "/home/ec2-user/repository/dist" ]; then echo "dist directory exists"; else echo "dist directory does not exist"; exit 1; fi

      - name: Copy dist folder to repository
        run: |
          sudo cp -r /home/ec2-user/repository/dist /home/ec2-user/repository/dist

      - name: Set permissions for Nginx
        run: |
          sudo chown -R nginx:nginx /home/ec2-user/repository/dist
          sudo chmod -R 755 /home/ec2-user/repository/dist
