name: Deploy to Amazon Linux

on:
  # Trigger on push to the specific branch
  push:
    branches:
      - master

  # Allow manual trigger for testing purposes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Print Node.js version
        run: node -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove existing repository directory
        run: |
          sudo rm -rf /home/ec2-user/repository || true

      - name: Create repository directory and copy code
        run: |
          mkdir -p /home/ec2-user/repository
          cp -r . /home/ec2-user/repository/
          cd /home/ec2-user/repository

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      - name: Set permissions for Nginx
        run: |
          sudo chown -R nginx:nginx /home/ec2-user/repository/dist
          sudo chmod -R 755 /home/ec2-user/repository/dist
