name: Deploy to Amazon Linux

on:
  # Trigger on push to the specific branch
  push:
    branches:
      - master

  # Allow manual trigger for testing purposes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Print Node.js version
        run: node -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move code to /home/ec2-user
        run: |
          mkdir -p /home/ec2-user/repository
          mv * /home/ec2-user/repository
          cd /home/ec2-user/repository

      - name: Remove existing dist directory
        run: |
          rm -rf /home/ec2-user/repository/dist

      - name: Install dependencies
        run: |
          cd /home/ec2-user/repository
          npm install

      - name: Build project
        run: |
          cd /home/ec2-user/repository
          npm run build

      - name: Set permissions for Nginx
        run: |
          sudo chown -R nginx:nginx /home/ec2-user/repository/dist
          sudo chmod -R 755 /home/ec2-user/repository/dist
