name: Deploy to Amazon Linux

on:
  # Trigger on push to the specific branch
  push:
    branches:
      - master

  # Allow manual trigger for testing purposes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Print Node.js version
        run: node -v

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: /home/ec2-user/repository  # Specify the path where you want to clone the repo

      - name: Install dependencies
        run: |
          cd /home/ec2-user/repository
          npm install

      - name: Build project
        run: |
          cd /home/ec2-user/repository
          npm run build
