
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
   
    steps:
    - name: NVM Setup Node
      uses: irby/setup-node-nvm@master
      with:
        node-version: 12


 

  
