
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
   
    steps:
    - name: NVM Setup Node
      run: pwd
      
    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v5
       node-version:12

 

  
